theme: minima
title: SBN CLASSES
author: Sunil Dhaka
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the offical page of SBN Classes. We are an education platform. Here you can find our all social media pages. And also all 
  the youtube videos from Hira Dhaka and Er. Gopal Jangir Sir.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
